FROM node:16-alpine as base
RUN npm install --silent -g pnpm@7.20.0

FROM base AS build
WORKDIR /app

COPY pnpm-lock.yaml .
COPY patches ./patches

RUN pnpm fetch

COPY bot ./bot
COPY common ./common
COPY *.json *.yaml ./

RUN pnpm --filter tachi-bot... --filter . install --offline --frozen-lockfile
RUN pnpm --filter tachi-bot... -r build

FROM base AS app
COPY --from=build /app /app
WORKDIR /app/bot

ENV NODE_PATH=js/
CMD ["node", "js/main.js"]
