FROM node:20-alpine AS base

RUN npm install --silent -g pnpm@8.15.6

FROM base AS build
WORKDIR /app

COPY pnpm-lock.yaml .
COPY patches ./patches

RUN pnpm fetch

COPY client ./client
COPY common ./common
COPY *.json *.yaml ./

RUN pnpm --filter tachi-client... --filter . install --offline --frozen-lockfile

WORKDIR /app/client

CMD ["pnpm", "start"]