/** @TODO Potentially re-work this to only run on PROD env, handy for DEV env! **/
export const allowedChannels = ["876321394005254214"];

export enum LoggerLayers {
	client = "client",
	slashCommands = "slashCommands",
	server = "server",
	serverAuth = "serverAuth",
	botConfigSetup = "botConfigSetup",
	tachiFetch = "tachiFetch",
	profile = "profile",
	selectInteractionHandler = "selectInteractionHandler",
	buildProfileEmbed = "buildProfileEmbed",
	chartSearch = "chartSearch",
	buildChartEmbed = "buildChartEmbed",
	tachiAuth = "tachiAuth",
	database = "database",
	databaseQuery = "databaseQuery",
}

export const theFunny = [
	"because 352 people are in this server and they can see that i was looking at chokers and thigh highs",
	"Invalid command. (No similar commands found, either.)",
	"**You may be a victim of software counterfeiting.**\n\nTo use all Microsoft Windows® features, such as all updates\nfrom Windows Update; get all the latest updates; and receive\nproduct support, your copy of Microsoft Windows® must be\nvalidated as genuine.\n\n__Go online and resolve now__",
	"The Score Tracking Man He Sees Everything Like This",
	"'DROP TABLE scores;--",
	"Blessed Data",
	"No Nonsense",
	"Maybe a little nonsense",
	"Mr Worldwide",
	"Ceci n'est pas un splash text",
	"mowgli, loOK OUT",
	"Swish swoosh pew pew",
	"All this scratching is making me itch",
	"Pace yourself",
	"What is this, a crossover episode?",
	"npm install humor",
	"OKNOTOK",
	"Unlimited multiplication of money up to 300%!",
	"What happens if I print a dictionary?",
	"Whatever people say I am...",
	"When the four corners of this coccoon collide...",
	"WE CAN DO BETTER",
	"WE WILL DO BETTER",
	"BREAK YOUR NIHILISM",
	"float chordjack = jack * 0.75f;",
	"malicious walls",
	"my computer called cheesebuger",
	"Unban me from Quaver",
	"...we came in?",
	"isn't this where...",
	"You are simply neglecting the law of large numbers.",
	"I'm using tilt controls!",
	"Relax yourself, girl, please set-tle down",
	"Michael Jackson IS Monty Python.",
	"1.01^365",
	"WARNING: That is not falco",
	"it's been one week since ya looked at me",
	"IT AIN'T NO EASY GRAB THEY GOT T",
	"AUTOGLASS REPAIR",
	"AUTOGLASS REPLACE",
	"turn on RANDOM!",
	"It is deliberate.",
	"Buy the golden ninja pack!",
	"WITHIN REASON!",
	"Put the maid dress on.",
	"And it just happens to be fantastically enjoyable.",
	"Touch the statue. I will forgive you.",
	"https://github.com/EpicGames/Signup/pull/10",
	"Have you tried PNPM?",
	"MongoDB is web scale, actually.",
	"▼LTRA ▼IOLENCE EDITION",
	"It's all about the CEO grindset.",
	"through ivy - out middle",
	"The graphics. That's what it's really about.",
	"you could be playing mario galaxy right now",
	"...When yours just crashes?",
	"My Beautiful Score Tracking Fantasy",
	"The Supercharged Score Tracker.",
	"Play ULTRAKILL.",
	"A Cutting-Edge Score Tracker (heh).",
	"Winnipeg is a warm, nice place to live.",
	"zkldi once said: i piss my bed twice a month and that really annoys me",
	"I accidentally the score tracker.",
	"~𝒕𝒉𝒆 𝒈𝒆𝒂𝒓𝒔 𝒕𝒖𝒓𝒏 𝒐𝒏𝒄𝒆 𝒎𝒐𝒓𝒆~",
	"come on down",
	"The preparation for a dive is always a tense time.",
	"Music Is Math",
	"The public gets what the public wants!",
	"Formerly Chucks",
	"Node.js Is Bad Ass Rock Star Tech",
	"i'm obligated to ask for you to seek immediate psychological attention",
	"Is IIDX still a good game or are you all basically stupid?",
	"A point in the horizon, a melting scene from your childhood. Your mortality is showing a frantic drift towards nothing, biology doomed to an infinite recursive loop. Teeth with teeth with teeth. Take a bite. Serene scene of a coastal town, warmth of the sun. Bitter tears. Lust for power. This is where you abandoned your dreams. You are a high net worth individual, an expanding vortex of pathetic trauma. Finally a beautiful fucking nerve ape. A pure soul is born, its neurotransactions stutter into being. 30583750937509353 operations per nanosecond. Beauty eludes your porous mind.\n\nThe value of Life is negative. The balance of being is rotated by 38 degrees. The surface is full of cracks, a turgid light shines through. Fleshy primordial bodies sluggishly roll down the slope. Only you slide upwards, with a celestial step. You become beautified, a saintly figure. Your pristine idiocy reveals a safe path through the impenetrable fog of life. Your dull sword cuts through the weak tendons and membranes of the garden of corruption. Sit on the throne of contentment and ferment. Inspect the eternal blue skies of your kingdom. You come to a realization. You pick up and onion and begin peeling.\n\nOnion layer one. Onion layer two. Onion layer three ... Onion layer n^n. Aeons have passed and the onion is fully peeled. Nothing remains. It's perfect. You get lost in the point that remains where the onion used to be. Synaptic cascade, neurological catastrophe. The point becomes infinitely dense, the universe condenses into a unicellular being. It screams sin. It craves happiness. It's done with this world. It tries to commit suicide but it fails. Sad pathetic mess. You feel pity and disgust but in a way only a being of pure grace can. In your violent mercy you terminate the worldlife.",
	"Please do not reply to or quote my posts in the future.",
];
