[private]
interactive:
	-@cd ../ && just

# Run the server interactively. Changes made to files will trigger reloads.
start:
	pnpm dev

# Test the server.
test: lint typecheck
	pnpm test

lint:
	pnpm lint

typecheck:
	pnpm typecheck

# Clean up the code and fix any automatically fixable mistakes.
lintfix:
	pnpm lint-fix