[private]
interactive:
	-@cd ../ && just

# Run the server interactively. Changes made to files will trigger reloads.
start:
	pnpm dev

# Test the server.
test:
	pnpm lint
	pnpm test

# Clean up the code and fix any automatically fixable mistakes.
lintfix:
	pnpm lint-fix