"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.GetGamePTConfig = exports.GetGameConfig = exports.COLOUR_SET = void 0;
const game_classes_1 = require("../game-classes");
/**
 * A collection of CSS colours we want to work with.
 */
exports.COLOUR_SET = {
    gray: "rgba(105, 105, 105, 1)",
    maroon: "rgba(85, 17, 17, 1)",
    red: "rgba(170, 85, 85, 1)",
    paleGreen: "rgba(142,174,79, 1)",
    paleBlue: "rgba(92, 97, 153, 1)",
    green: "rgba(50, 205, 50, 1)",
    blue: "rgba(70, 130, 180, 1)",
    gold: "rgba(255, 215, 0, 1)",
    vibrantYellow: "rgba(245, 229, 27, 1)",
    teal: "rgba(127, 255, 212, 1)",
    white: "rgba(192, 192, 192, 1)",
    purple: "rgba(153, 50, 204, 1)",
    vibrantPurple: "rgba(161, 23, 230, 1)",
    paleOrange: "rgba(235, 151, 78, 1)",
    orange: "rgba(248, 148, 6, 1)",
    vibrantOrange: "rgba(248, 175, 6, 1)",
    vibrantBlue: "rgba(43, 149, 237, 1)",
    vibrantGreen: "rgba(26, 232, 26, 1)",
};
const GAME_CONFIGS = {
    iidx: {
        defaultPlaytype: "SP",
        name: "beatmania IIDX",
        internalName: "iidx",
        validPlaytypes: ["SP", "DP"],
    },
    museca: {
        defaultPlaytype: "Single",
        name: "MÚSECA",
        internalName: "museca",
        validPlaytypes: ["Single"],
    },
    chunithm: {
        defaultPlaytype: "Single",
        name: "CHUNITHM",
        internalName: "chunithm",
        validPlaytypes: ["Single"],
    },
    ddr: {
        defaultPlaytype: "SP",
        name: "DDR",
        internalName: "ddr",
        validPlaytypes: ["SP", "DP"],
    },
    bms: {
        defaultPlaytype: "7K",
        name: "BMS",
        internalName: "bms",
        validPlaytypes: ["7K", "14K"],
    },
    gitadora: {
        defaultPlaytype: "Dora",
        name: "GITADORA",
        internalName: "gitadora",
        validPlaytypes: ["Gita", "Dora"],
    },
    // jubeat: {
    //     defaultPlaytype: "Single",
    //     name: "jubeat",
    //     internalName: "jubeat",
    //     validPlaytypes: ["Single"],
    // },
    maimai: {
        defaultPlaytype: "Single",
        name: "maimai",
        internalName: "maimai",
        validPlaytypes: ["Single"],
    },
    // popn: {
    //     defaultPlaytype: "9B",
    //     name: "pop'n music",
    //     internalName: "popn", // note: KAI servers use pnm as a name.
    //     validPlaytypes: ["9B"],
    // },
    sdvx: {
        defaultPlaytype: "Single",
        name: "SOUND VOLTEX",
        internalName: "sdvx",
        validPlaytypes: ["Single"],
    },
    usc: {
        defaultPlaytype: "Single",
        name: "unnamed_sdvx_clone",
        internalName: "usc",
        validPlaytypes: ["Single"],
    },
};
const GAME_PT_CONFIGS = {
    "iidx:SP": {
        idString: "iidx:SP",
        percentMax: 100,
        defaultScoreRatingAlg: "ktRating",
        defaultSessionRatingAlg: "ktRating",
        defaultProfileRatingAlg: "ktRating",
        scoreRatingAlgs: ["ktRating", "ktLampRating", "BPI"],
        sessionRatingAlgs: ["ktRating", "ktLampRating", "BPI"],
        profileRatingAlgs: ["ktRating", "ktLampRating", "BPI"],
        difficulties: ["BEGINNER", "NORMAL", "HYPER", "ANOTHER", "LEGGENDARIA"],
        shortDifficulties: {
            BEGINNER: "B",
            NORMAL: "N",
            HYPER: "H",
            ANOTHER: "A",
            LEGGENDARIA: "L",
        },
        defaultDifficulty: "ANOTHER",
        difficultyColours: {
            BEGINNER: exports.COLOUR_SET.paleGreen,
            NORMAL: exports.COLOUR_SET.blue,
            HYPER: exports.COLOUR_SET.orange,
            ANOTHER: exports.COLOUR_SET.red,
            LEGGENDARIA: exports.COLOUR_SET.purple,
        },
        grades: ["F", "E", "D", "C", "B", "A", "AA", "AAA", "MAX-", "MAX"],
        gradeColours: {
            F: exports.COLOUR_SET.gray,
            E: exports.COLOUR_SET.red,
            D: exports.COLOUR_SET.maroon,
            C: exports.COLOUR_SET.purple,
            B: exports.COLOUR_SET.paleBlue,
            A: exports.COLOUR_SET.green,
            AA: exports.COLOUR_SET.blue,
            AAA: exports.COLOUR_SET.gold,
            "MAX-": exports.COLOUR_SET.teal,
            MAX: exports.COLOUR_SET.white,
        },
        clearGrade: "A",
        gradeBoundaries: [0, 22.22, 33.33, 44.44, 55.55, 66.66, 77.77, 88.88, 94.44, 100.0],
        lamps: [
            "NO PLAY",
            "FAILED",
            "ASSIST CLEAR",
            "EASY CLEAR",
            "CLEAR",
            "HARD CLEAR",
            "EX HARD CLEAR",
            "FULL COMBO",
        ],
        lampColours: {
            "NO PLAY": exports.COLOUR_SET.gray,
            FAILED: exports.COLOUR_SET.red,
            "ASSIST CLEAR": exports.COLOUR_SET.purple,
            "EASY CLEAR": exports.COLOUR_SET.green,
            CLEAR: exports.COLOUR_SET.blue,
            "HARD CLEAR": exports.COLOUR_SET.orange,
            "EX HARD CLEAR": exports.COLOUR_SET.gold,
            "FULL COMBO": exports.COLOUR_SET.teal,
        },
        clearLamp: "CLEAR",
        supportedClasses: ["dan"],
        classHumanisedFormat: {
            dan: game_classes_1.IIDXDans,
        },
        supportsESD: true,
        judgementWindows: [
            { name: "PGREAT", msBorder: 16.667, value: 2 },
            { name: "GREAT", msBorder: 33.333, value: 1 },
            { name: "GOOD", msBorder: 116.667, value: 0 },
        ],
        judgements: ["pgreat", "great", "good", "bad", "poor"],
        defaultTable: "Levels (N-1)",
        scoreBucket: "lamp",
    },
    "iidx:DP": {
        idString: "iidx:DP",
        percentMax: 100,
        defaultScoreRatingAlg: "ktRating",
        defaultSessionRatingAlg: "ktRating",
        defaultProfileRatingAlg: "ktRating",
        scoreRatingAlgs: ["ktRating", "ktLampRating", "BPI"],
        sessionRatingAlgs: ["ktRating", "ktLampRating", "BPI"],
        profileRatingAlgs: ["ktRating", "ktLampRating", "BPI"],
        difficulties: ["NORMAL", "HYPER", "ANOTHER", "LEGGENDARIA"],
        shortDifficulties: {
            NORMAL: "N",
            HYPER: "H",
            ANOTHER: "A",
            LEGGENDARIA: "L",
        },
        defaultDifficulty: "ANOTHER",
        difficultyColours: {
            NORMAL: exports.COLOUR_SET.blue,
            HYPER: exports.COLOUR_SET.orange,
            ANOTHER: exports.COLOUR_SET.red,
            LEGGENDARIA: exports.COLOUR_SET.purple,
        },
        grades: ["F", "E", "D", "C", "B", "A", "AA", "AAA", "MAX-", "MAX"],
        gradeColours: {
            F: exports.COLOUR_SET.gray,
            E: exports.COLOUR_SET.red,
            D: exports.COLOUR_SET.maroon,
            C: exports.COLOUR_SET.purple,
            B: exports.COLOUR_SET.paleBlue,
            A: exports.COLOUR_SET.green,
            AA: exports.COLOUR_SET.blue,
            AAA: exports.COLOUR_SET.gold,
            "MAX-": exports.COLOUR_SET.teal,
            MAX: exports.COLOUR_SET.white,
        },
        clearGrade: "A",
        gradeBoundaries: [0, 22.22, 33.33, 44.44, 55.55, 66.66, 77.77, 88.88, 94.44, 100.0],
        lamps: [
            "NO PLAY",
            "FAILED",
            "ASSIST CLEAR",
            "EASY CLEAR",
            "CLEAR",
            "HARD CLEAR",
            "EX HARD CLEAR",
            "FULL COMBO",
        ],
        lampColours: {
            "NO PLAY": exports.COLOUR_SET.gray,
            FAILED: exports.COLOUR_SET.red,
            "ASSIST CLEAR": exports.COLOUR_SET.purple,
            "EASY CLEAR": exports.COLOUR_SET.green,
            CLEAR: exports.COLOUR_SET.blue,
            "HARD CLEAR": exports.COLOUR_SET.orange,
            "EX HARD CLEAR": exports.COLOUR_SET.gold,
            "FULL COMBO": exports.COLOUR_SET.teal,
        },
        clearLamp: "CLEAR",
        supportedClasses: ["dan"],
        classHumanisedFormat: {
            dan: game_classes_1.IIDXDans,
        },
        supportsESD: true,
        judgementWindows: [
            { name: "PGREAT", msBorder: 16.667, value: 2 },
            { name: "GREAT", msBorder: 33.333, value: 1 },
            { name: "GOOD", msBorder: 116.667, value: 0 },
        ],
        judgements: ["pgreat", "great", "good", "bad", "poor"],
        defaultTable: "Levels (N-1)",
        scoreBucket: "lamp",
    },
    "chunithm:Single": {
        idString: "chunithm:Single",
        percentMax: 101,
        defaultScoreRatingAlg: "rating",
        defaultSessionRatingAlg: "naiveRating",
        defaultProfileRatingAlg: "naiveRating",
        scoreRatingAlgs: ["rating"],
        sessionRatingAlgs: ["naiveRating"],
        profileRatingAlgs: ["naiveRating"],
        difficulties: ["BASIC", "ADVANCED", "EXPERT", "MASTER", "WORLD'S END"],
        shortDifficulties: {
            BASIC: "B",
            ADVANCED: "A",
            EXPERT: "E",
            MASTER: "M",
            "WORLD'S END": "W",
        },
        defaultDifficulty: "MASTER",
        difficultyColours: {
            BASIC: exports.COLOUR_SET.blue,
            ADVANCED: exports.COLOUR_SET.orange,
            EXPERT: exports.COLOUR_SET.red,
            MASTER: exports.COLOUR_SET.purple,
            "WORLD'S END": exports.COLOUR_SET.vibrantYellow,
        },
        grades: ["D", "C", "B", "BB", "BBB", "A", "AA", "AAA", "S", "SS", "SSS"],
        gradeColours: {
            D: exports.COLOUR_SET.red,
            C: exports.COLOUR_SET.purple,
            B: exports.COLOUR_SET.paleBlue,
            BB: exports.COLOUR_SET.blue,
            BBB: exports.COLOUR_SET.vibrantBlue,
            A: exports.COLOUR_SET.paleGreen,
            AA: exports.COLOUR_SET.green,
            AAA: exports.COLOUR_SET.vibrantGreen,
            S: exports.COLOUR_SET.vibrantOrange,
            SS: exports.COLOUR_SET.vibrantYellow,
            SSS: exports.COLOUR_SET.teal,
        },
        clearGrade: "A",
        gradeBoundaries: [0, 50, 60, 70, 80, 90, 92.5, 95.0, 97.5, 100, 107.5, 101],
        lamps: ["FAILED", "CLEAR", "FULL COMBO", "ALL JUSTICE", "ALL JUSTICE CRITICAL"],
        lampColours: {
            FAILED: exports.COLOUR_SET.red,
            CLEAR: exports.COLOUR_SET.paleGreen,
            "FULL COMBO": exports.COLOUR_SET.paleBlue,
            "ALL JUSTICE": exports.COLOUR_SET.gold,
            "ALL JUSTICE CRITICAL": exports.COLOUR_SET.white,
        },
        clearLamp: "CLEAR",
        supportedClasses: [],
        classHumanisedFormat: {},
        supportsESD: false,
        judgements: ["jcrit", "justice", "attack", "miss"],
        defaultTable: "Levels (N-1)",
        scoreBucket: "grade",
    },
    "sdvx:Single": {
        idString: "sdvx:Single",
        percentMax: 100,
        defaultScoreRatingAlg: "VF6",
        defaultSessionRatingAlg: "ProfileVF6",
        defaultProfileRatingAlg: "VF6",
        scoreRatingAlgs: ["VF6"],
        sessionRatingAlgs: ["ProfileVF6", "VF6"],
        profileRatingAlgs: ["VF6"],
        difficulties: ["NOV", "ADV", "EXH", "INF", "GRV", "HVN", "VVD", "MXM"],
        shortDifficulties: {},
        defaultDifficulty: "EXH",
        difficultyColours: {
            NOV: exports.COLOUR_SET.purple,
            ADV: exports.COLOUR_SET.vibrantYellow,
            EXH: exports.COLOUR_SET.red,
            INF: "TODO",
            GRV: exports.COLOUR_SET.orange,
            HVN: exports.COLOUR_SET.teal,
            VVD: "TODO",
            MXM: exports.COLOUR_SET.white,
        },
        grades: ["D", "C", "B", "A", "A+", "AA", "AA+", "AAA", "AAA+", "S"],
        gradeColours: {
            D: exports.COLOUR_SET.gray,
            C: exports.COLOUR_SET.red,
            B: exports.COLOUR_SET.maroon,
            A: exports.COLOUR_SET.paleBlue,
            "A+": exports.COLOUR_SET.blue,
            AA: exports.COLOUR_SET.paleGreen,
            "AA+": exports.COLOUR_SET.green,
            AAA: exports.COLOUR_SET.gold,
            "AAA+": exports.COLOUR_SET.vibrantYellow,
            S: exports.COLOUR_SET.teal,
        },
        clearGrade: "A",
        gradeBoundaries: [0, 70, 80, 87, 90, 93, 95, 97, 98, 99],
        lamps: ["FAILED", "CLEAR", "EXCESSIVE CLEAR", "ULTIMATE CHAIN", "PERFECT ULTIMATE CHAIN"],
        lampColours: {
            FAILED: exports.COLOUR_SET.red,
            CLEAR: exports.COLOUR_SET.green,
            "EXCESSIVE CLEAR": exports.COLOUR_SET.orange,
            "ULTIMATE CHAIN": exports.COLOUR_SET.teal,
            "PERFECT ULTIMATE CHAIN": exports.COLOUR_SET.gold,
        },
        clearLamp: "CLEAR",
        supportedClasses: ["dan", "vfClass"],
        classHumanisedFormat: {
            dan: game_classes_1.SDVXDans,
            vfClass: game_classes_1.SDVXVFClasses,
        },
        supportsESD: false,
        judgements: ["critical", "near", "miss"],
        defaultTable: "Levels (N-1)",
        scoreBucket: "grade",
    },
    "usc:Single": {
        idString: "usc:Single",
        percentMax: 100,
        defaultScoreRatingAlg: "VF6",
        defaultSessionRatingAlg: "ProfileVF6",
        defaultProfileRatingAlg: "VF6",
        scoreRatingAlgs: ["VF6"],
        sessionRatingAlgs: ["ProfileVF6", "VF6"],
        profileRatingAlgs: ["VF6"],
        difficulties: ["NOV", "ADV", "EXH", "INF"],
        shortDifficulties: {},
        defaultDifficulty: "EXH",
        difficultyColours: {
            NOV: exports.COLOUR_SET.purple,
            ADV: exports.COLOUR_SET.vibrantYellow,
            EXH: exports.COLOUR_SET.red,
            INF: "TODO", // colour set light pink
        },
        grades: ["D", "C", "B", "A", "A+", "AA", "AA+", "AAA", "AAA+", "S"],
        gradeColours: {
            D: exports.COLOUR_SET.gray,
            C: exports.COLOUR_SET.red,
            B: exports.COLOUR_SET.maroon,
            A: exports.COLOUR_SET.paleBlue,
            "A+": exports.COLOUR_SET.blue,
            AA: exports.COLOUR_SET.paleGreen,
            "AA+": exports.COLOUR_SET.green,
            AAA: exports.COLOUR_SET.gold,
            "AAA+": exports.COLOUR_SET.vibrantYellow,
            S: exports.COLOUR_SET.teal,
        },
        clearGrade: "A",
        gradeBoundaries: [0, 70, 80, 87, 90, 93, 95, 97, 98, 99],
        lamps: ["FAILED", "CLEAR", "EXCESSIVE CLEAR", "ULTIMATE CHAIN", "PERFECT ULTIMATE CHAIN"],
        lampColours: {
            FAILED: exports.COLOUR_SET.red,
            CLEAR: exports.COLOUR_SET.green,
            "EXCESSIVE CLEAR": exports.COLOUR_SET.orange,
            "ULTIMATE CHAIN": exports.COLOUR_SET.teal,
            "PERFECT ULTIMATE CHAIN": exports.COLOUR_SET.gold,
        },
        clearLamp: "CLEAR",
        supportedClasses: [],
        classHumanisedFormat: {},
        supportsESD: false,
        judgements: ["critical", "near", "miss"],
        defaultTable: "Levels (N-1)",
        scoreBucket: "grade",
    },
    "museca:Single": {
        idString: "museca:Single",
        percentMax: 100,
        defaultScoreRatingAlg: "ktRating",
        defaultSessionRatingAlg: "ktRating",
        defaultProfileRatingAlg: "ktRating",
        scoreRatingAlgs: ["ktRating"],
        sessionRatingAlgs: ["ktRating"],
        profileRatingAlgs: ["ktRating"],
        difficulties: ["Green", "Yellow", "Red"],
        shortDifficulties: { Green: "G", Yellow: "Y", Red: "R" },
        defaultDifficulty: "Red",
        difficultyColours: {
            Green: exports.COLOUR_SET.green,
            Yellow: exports.COLOUR_SET.vibrantYellow,
            Red: exports.COLOUR_SET.red,
        },
        grades: ["没", "拙", "凡", "佳", "良", "優", "秀", "傑", "傑G"],
        gradeColours: {
            没: exports.COLOUR_SET.gray,
            拙: exports.COLOUR_SET.maroon,
            凡: exports.COLOUR_SET.red,
            佳: exports.COLOUR_SET.paleGreen,
            良: exports.COLOUR_SET.paleBlue,
            優: exports.COLOUR_SET.green,
            秀: exports.COLOUR_SET.blue,
            傑: exports.COLOUR_SET.teal,
            傑G: exports.COLOUR_SET.gold,
        },
        clearGrade: "良",
        gradeBoundaries: [0, 60, 70, 80, 85, 90, 95, 97.5, 100],
        lamps: ["FAILED", "CLEAR", "CONNECT ALL", "PERFECT CONNECT ALL"],
        lampColours: {
            FAILED: exports.COLOUR_SET.red,
            CLEAR: exports.COLOUR_SET.green,
            "CONNECT ALL": exports.COLOUR_SET.teal,
            "PERFECT CONNECT ALL": exports.COLOUR_SET.gold,
        },
        clearLamp: "CLEAR",
        supportedClasses: [],
        classHumanisedFormat: {},
        supportsESD: true,
        judgementWindows: [
            { name: "CRITICAL", msBorder: 33.333, value: 2 },
            { name: "NEAR", msBorder: 66.667, value: 1 },
        ],
        judgements: ["critical", "near", "miss"],
        defaultTable: "Levels (N-1)",
        scoreBucket: "grade",
    },
    "bms:7K": {
        idString: "bms:7K",
        percentMax: 100,
        defaultScoreRatingAlg: "sieglinde",
        defaultSessionRatingAlg: "sieglinde",
        defaultProfileRatingAlg: "sieglinde",
        scoreRatingAlgs: ["sieglinde"],
        sessionRatingAlgs: ["sieglinde"],
        profileRatingAlgs: ["sieglinde"],
        difficulties: ["CHART"],
        shortDifficulties: {},
        defaultDifficulty: "CHART",
        difficultyColours: {
            CHART: null,
        },
        grades: ["F", "E", "D", "C", "B", "A", "AA", "AAA", "MAX-", "MAX"],
        gradeColours: {
            F: exports.COLOUR_SET.gray,
            E: exports.COLOUR_SET.red,
            D: exports.COLOUR_SET.maroon,
            C: exports.COLOUR_SET.purple,
            B: exports.COLOUR_SET.paleBlue,
            A: exports.COLOUR_SET.green,
            AA: exports.COLOUR_SET.blue,
            AAA: exports.COLOUR_SET.gold,
            "MAX-": exports.COLOUR_SET.teal,
            MAX: exports.COLOUR_SET.white,
        },
        clearGrade: "A",
        gradeBoundaries: [0, 22.22, 33.33, 44.44, 55.55, 66.66, 77.77, 88.88, 94.44, 100.0],
        lamps: [
            "NO PLAY",
            "FAILED",
            "ASSIST CLEAR",
            "EASY CLEAR",
            "CLEAR",
            "HARD CLEAR",
            "EX HARD CLEAR",
            "FULL COMBO",
        ],
        lampColours: {
            "NO PLAY": exports.COLOUR_SET.gray,
            FAILED: exports.COLOUR_SET.red,
            "ASSIST CLEAR": exports.COLOUR_SET.purple,
            "EASY CLEAR": exports.COLOUR_SET.green,
            CLEAR: exports.COLOUR_SET.blue,
            "HARD CLEAR": exports.COLOUR_SET.orange,
            "EX HARD CLEAR": exports.COLOUR_SET.gold,
            "FULL COMBO": exports.COLOUR_SET.teal,
        },
        clearLamp: "CLEAR",
        supportedClasses: ["genocideDan", "stslDan"],
        classHumanisedFormat: {
            genocideDan: game_classes_1.BMSGenocideDans,
            stslDan: game_classes_1.BMSStSlDans,
        },
        supportsESD: false,
        judgements: ["pgreat", "great", "good", "bad", "poor"],
        defaultTable: "Insane",
        scoreBucket: "lamp",
    },
    "bms:14K": {
        idString: "bms:14K",
        percentMax: 100,
        defaultScoreRatingAlg: "sieglinde",
        defaultSessionRatingAlg: "sieglinde",
        defaultProfileRatingAlg: "sieglinde",
        scoreRatingAlgs: ["sieglinde"],
        sessionRatingAlgs: ["sieglinde"],
        profileRatingAlgs: ["sieglinde"],
        difficulties: ["CHART"],
        shortDifficulties: {},
        defaultDifficulty: "CHART",
        difficultyColours: {
            CHART: null,
        },
        grades: ["F", "E", "D", "C", "B", "A", "AA", "AAA", "MAX-", "MAX"],
        gradeColours: {
            F: exports.COLOUR_SET.gray,
            E: exports.COLOUR_SET.red,
            D: exports.COLOUR_SET.maroon,
            C: exports.COLOUR_SET.purple,
            B: exports.COLOUR_SET.paleBlue,
            A: exports.COLOUR_SET.green,
            AA: exports.COLOUR_SET.blue,
            AAA: exports.COLOUR_SET.gold,
            "MAX-": exports.COLOUR_SET.teal,
            MAX: exports.COLOUR_SET.white,
        },
        clearGrade: "A",
        gradeBoundaries: [0, 22.22, 33.33, 44.44, 55.55, 66.66, 77.77, 88.88, 94.44, 100.0],
        lamps: [
            "NO PLAY",
            "FAILED",
            "ASSIST CLEAR",
            "EASY CLEAR",
            "CLEAR",
            "HARD CLEAR",
            "EX HARD CLEAR",
            "FULL COMBO",
        ],
        lampColours: {
            "NO PLAY": exports.COLOUR_SET.gray,
            FAILED: exports.COLOUR_SET.red,
            "ASSIST CLEAR": exports.COLOUR_SET.purple,
            "EASY CLEAR": exports.COLOUR_SET.green,
            CLEAR: exports.COLOUR_SET.blue,
            "HARD CLEAR": exports.COLOUR_SET.orange,
            "EX HARD CLEAR": exports.COLOUR_SET.gold,
            "FULL COMBO": exports.COLOUR_SET.teal,
        },
        clearLamp: "CLEAR",
        supportedClasses: ["genocideDan"],
        classHumanisedFormat: {
            genocideDan: game_classes_1.BMSGenocideDans,
        },
        supportsESD: false,
        judgements: ["pgreat", "great", "good", "bad", "poor"],
        defaultTable: "Insane",
        scoreBucket: "lamp",
    },
    "ddr:SP": {
        idString: "ddr:SP",
        percentMax: 100,
        defaultScoreRatingAlg: "ktRating",
        defaultSessionRatingAlg: "ktRating",
        defaultProfileRatingAlg: "ktRating",
        scoreRatingAlgs: ["MFCP", "ktRating"],
        sessionRatingAlgs: ["MFCP", "ktRating"],
        profileRatingAlgs: ["MFCP", "ktRating"],
        difficulties: ["BEGINNER", "BASIC", "DIFFICULT", "EXPERT", "CHALLENGE"],
        shortDifficulties: {
            BEGINNER: "b",
            BASIC: "B",
            DIFFICULT: "D",
            EXPERT: "E",
            CHALLENGE: "C",
        },
        defaultDifficulty: "EXPERT",
        difficultyColours: {
            BEGINNER: exports.COLOUR_SET.paleBlue,
            BASIC: exports.COLOUR_SET.orange,
            DIFFICULT: exports.COLOUR_SET.red,
            EXPERT: exports.COLOUR_SET.green,
            CHALLENGE: exports.COLOUR_SET.purple,
        },
        grades: [
            "D",
            "D+",
            "C-",
            "C",
            "C+",
            "B-",
            "B",
            "B+",
            "A-",
            "A",
            "A+",
            "AA-",
            "AA",
            "AA+",
            "AAA",
        ],
        gradeColours: {
            D: exports.COLOUR_SET.gray,
            "D+": exports.COLOUR_SET.maroon,
            "C-": exports.COLOUR_SET.red,
            C: exports.COLOUR_SET.purple,
            "C+": exports.COLOUR_SET.vibrantPurple,
            "B-": exports.COLOUR_SET.paleBlue,
            B: exports.COLOUR_SET.blue,
            "B+": exports.COLOUR_SET.vibrantBlue,
            "A-": exports.COLOUR_SET.paleGreen,
            A: exports.COLOUR_SET.green,
            "A+": exports.COLOUR_SET.vibrantGreen,
            "AA-": exports.COLOUR_SET.paleOrange,
            AA: exports.COLOUR_SET.orange,
            "AA+": exports.COLOUR_SET.vibrantOrange,
            AAA: exports.COLOUR_SET.gold,
        },
        clearGrade: "A",
        gradeBoundaries: [0, 55, 59, 60, 65, 69, 70, 75, 79, 80, 85, 89, 90, 95, 99],
        lamps: [
            "FAILED",
            "CLEAR",
            "LIFE4",
            "FULL COMBO",
            "GREAT FULL COMBO",
            "PERFECT FULL COMBO",
            "MARVELOUS FULL COMBO",
        ],
        lampColours: {
            FAILED: exports.COLOUR_SET.red,
            CLEAR: exports.COLOUR_SET.paleGreen,
            LIFE4: exports.COLOUR_SET.orange,
            "FULL COMBO": exports.COLOUR_SET.paleBlue,
            "GREAT FULL COMBO": exports.COLOUR_SET.green,
            "PERFECT FULL COMBO": exports.COLOUR_SET.gold,
            "MARVELOUS FULL COMBO": exports.COLOUR_SET.teal,
        },
        clearLamp: "CLEAR",
        supportedClasses: ["dan"],
        classHumanisedFormat: {
            dan: game_classes_1.DDRDans,
        },
        supportsESD: true,
        judgementWindows: [
            { name: "MARVELOUS", msBorder: 15, value: 3 },
            { name: "PERFECT", msBorder: 30, value: 2 },
            { name: "GREAT", msBorder: 59, value: 1 },
            { name: "GOOD", msBorder: 89, value: 0 },
            { name: "BAD", msBorder: 119, value: 0 },
        ],
        judgements: ["marvelous", "perfect", "great", "good", "boo", "miss", "ok", "ng"],
        defaultTable: "Levels (N-1)",
        scoreBucket: "lamp",
    },
    "ddr:DP": {
        idString: "ddr:DP",
        percentMax: 100,
        defaultScoreRatingAlg: "ktRating",
        defaultSessionRatingAlg: "ktRating",
        defaultProfileRatingAlg: "ktRating",
        scoreRatingAlgs: ["MFCP", "ktRating"],
        sessionRatingAlgs: ["MFCP", "ktRating"],
        profileRatingAlgs: ["MFCP", "ktRating"],
        difficulties: ["BASIC", "DIFFICULT", "EXPERT", "CHALLENGE"],
        shortDifficulties: {
            BASIC: "B",
            DIFFICULT: "D",
            EXPERT: "E",
            CHALLENGE: "C",
        },
        defaultDifficulty: "EXPERT",
        difficultyColours: {
            BASIC: exports.COLOUR_SET.orange,
            DIFFICULT: exports.COLOUR_SET.red,
            EXPERT: exports.COLOUR_SET.green,
            CHALLENGE: exports.COLOUR_SET.purple,
        },
        grades: [
            "D",
            "D+",
            "C-",
            "C",
            "C+",
            "B-",
            "B",
            "B+",
            "A-",
            "A",
            "A+",
            "AA-",
            "AA",
            "AA+",
            "AAA",
        ],
        gradeColours: {
            D: exports.COLOUR_SET.gray,
            "D+": exports.COLOUR_SET.maroon,
            "C-": exports.COLOUR_SET.red,
            C: exports.COLOUR_SET.purple,
            "C+": exports.COLOUR_SET.vibrantPurple,
            "B-": exports.COLOUR_SET.paleBlue,
            B: exports.COLOUR_SET.blue,
            "B+": exports.COLOUR_SET.vibrantBlue,
            "A-": exports.COLOUR_SET.paleGreen,
            A: exports.COLOUR_SET.green,
            "A+": exports.COLOUR_SET.vibrantGreen,
            "AA-": exports.COLOUR_SET.paleOrange,
            AA: exports.COLOUR_SET.orange,
            "AA+": exports.COLOUR_SET.vibrantOrange,
            AAA: exports.COLOUR_SET.gold,
        },
        clearGrade: "A",
        gradeBoundaries: [0, 55, 59, 60, 65, 69, 70, 75, 79, 80, 85, 89, 90, 95, 99],
        lamps: [
            "FAILED",
            "CLEAR",
            "LIFE4",
            "FULL COMBO",
            "GREAT FULL COMBO",
            "PERFECT FULL COMBO",
            "MARVELOUS FULL COMBO",
        ],
        lampColours: {
            FAILED: exports.COLOUR_SET.red,
            CLEAR: exports.COLOUR_SET.paleGreen,
            LIFE4: exports.COLOUR_SET.orange,
            "FULL COMBO": exports.COLOUR_SET.paleBlue,
            "GREAT FULL COMBO": exports.COLOUR_SET.green,
            "PERFECT FULL COMBO": exports.COLOUR_SET.gold,
            "MARVELOUS FULL COMBO": exports.COLOUR_SET.teal,
        },
        clearLamp: "CLEAR",
        supportedClasses: ["dan"],
        classHumanisedFormat: {
            dan: game_classes_1.DDRDans,
        },
        supportsESD: true,
        judgementWindows: [
            { name: "MARVELOUS", msBorder: 15, value: 3 },
            { name: "PERFECT", msBorder: 30, value: 2 },
            { name: "GREAT", msBorder: 59, value: 1 },
            { name: "GOOD", msBorder: 89, value: 0 },
            { name: "BAD", msBorder: 119, value: 0 },
        ],
        judgements: ["marvelous", "perfect", "great", "good", "boo", "miss", "ok", "ng"],
        defaultTable: "Levels (N-1)",
        scoreBucket: "lamp",
    },
    "maimai:Single": {
        idString: "maimai:Single",
        percentMax: 120,
        defaultScoreRatingAlg: "ktRating",
        defaultSessionRatingAlg: "ktRating",
        defaultProfileRatingAlg: "ktRating",
        scoreRatingAlgs: ["ktRating"],
        sessionRatingAlgs: ["ktRating"],
        profileRatingAlgs: ["ktRating"],
        difficulties: ["Easy", "Basic", "Advanced", "Expert", "Master", "Re:Master"],
        shortDifficulties: {
            Easy: "e",
            Basic: "B",
            Advanced: "A",
            Expert: "E",
            Master: "M",
            "Re:Master": "Re",
        },
        defaultDifficulty: "Master",
        difficultyColours: {
            Easy: exports.COLOUR_SET.blue,
            Basic: exports.COLOUR_SET.green,
            Advanced: exports.COLOUR_SET.orange,
            Expert: exports.COLOUR_SET.red,
            Master: exports.COLOUR_SET.purple,
            "Re:Master": exports.COLOUR_SET.white,
        },
        grades: ["F", "E", "D", "C", "B", "A", "AA", "AAA", "S", "S+", "SS", "SS+", "SSS", "SSS+"],
        gradeColours: {
            F: exports.COLOUR_SET.gray,
            E: exports.COLOUR_SET.red,
            D: exports.COLOUR_SET.maroon,
            C: exports.COLOUR_SET.purple,
            B: exports.COLOUR_SET.paleGreen,
            A: exports.COLOUR_SET.green,
            AA: exports.COLOUR_SET.paleBlue,
            AAA: exports.COLOUR_SET.blue,
            S: exports.COLOUR_SET.gold,
            "S+": exports.COLOUR_SET.vibrantYellow,
            SS: exports.COLOUR_SET.paleOrange,
            "SS+": exports.COLOUR_SET.orange,
            SSS: exports.COLOUR_SET.teal,
            "SSS+": exports.COLOUR_SET.white,
        },
        clearGrade: "A",
        // @hack Maimai's top grade depends on the chart's maximum percent
        // we just set it at percentMax, but it's not technically correct
        gradeBoundaries: [0, 10, 20, 40, 60, 80, 90, 94, 97, 98, 99, 99.5, 100, 120],
        lamps: ["FAILED", "CLEAR", "FULL COMBO", "ALL PERFECT", "ALL PERFECT+"],
        lampColours: {
            FAILED: exports.COLOUR_SET.red,
            CLEAR: exports.COLOUR_SET.green,
            "FULL COMBO": exports.COLOUR_SET.blue,
            "ALL PERFECT": exports.COLOUR_SET.gold,
            "ALL PERFECT+": exports.COLOUR_SET.teal,
        },
        clearLamp: "CLEAR",
        supportedClasses: [],
        classHumanisedFormat: {},
        supportsESD: false,
        judgements: ["perfect", "great", "good", "miss"],
        defaultTable: "Levels",
        scoreBucket: "grade",
    },
    "gitadora:Gita": {
        idString: "gitadora:Gita",
        percentMax: 100,
        defaultScoreRatingAlg: "skill",
        defaultSessionRatingAlg: "skill",
        defaultProfileRatingAlg: "skill",
        scoreRatingAlgs: ["skill"],
        sessionRatingAlgs: ["skill"],
        profileRatingAlgs: ["skill"],
        difficulties: [
            "BASIC",
            "ADVANCED",
            "EXTREME",
            "MASTER",
            "BASS BASIC",
            "BASS ADVANCED",
            "BASS EXTREME",
            "BASS MASTER",
        ],
        shortDifficulties: {
            BASIC: "G-BSC",
            ADVANCED: "G-ADV",
            EXTREME: "G-EXT",
            MASTER: "G-MAS",
            "BASS BASIC": "B-BSC",
            "BASS ADVANCED": "B-ADV",
            "BASS EXTREME": "B-EXT",
            "BASS MASTER": "B-MAS",
        },
        defaultDifficulty: "EXTREME",
        difficultyColours: {
            BASIC: exports.COLOUR_SET.blue,
            ADVANCED: exports.COLOUR_SET.orange,
            EXTREME: exports.COLOUR_SET.red,
            MASTER: exports.COLOUR_SET.purple,
            "BASS BASIC": exports.COLOUR_SET.vibrantBlue,
            "BASS ADVANCED": exports.COLOUR_SET.vibrantOrange,
            "BASS EXTREME": "todo",
            "BASS MASTER": exports.COLOUR_SET.vibrantPurple,
        },
        grades: ["C", "B", "A", "S", "SS", "MAX"],
        gradeColours: {
            C: exports.COLOUR_SET.purple,
            B: exports.COLOUR_SET.blue,
            A: exports.COLOUR_SET.green,
            S: exports.COLOUR_SET.orange,
            SS: exports.COLOUR_SET.gold,
            MAX: exports.COLOUR_SET.white,
        },
        clearGrade: "A",
        gradeBoundaries: [0, 63, 73, 80, 95, 100],
        lamps: ["FAILED", "CLEAR", "FULL COMBO", "EXCELLENT"],
        lampColours: {
            FAILED: exports.COLOUR_SET.red,
            CLEAR: exports.COLOUR_SET.blue,
            "FULL COMBO": exports.COLOUR_SET.teal,
            EXCELLENT: exports.COLOUR_SET.gold,
        },
        clearLamp: "CLEAR",
        supportedClasses: ["colour"],
        classHumanisedFormat: {
            colour: game_classes_1.GitadoraColours,
        },
        supportsESD: false,
        judgements: ["perfect", "great", "good", "ok", "miss"],
        defaultTable: "Levels (N-1)",
        scoreBucket: "grade",
    },
    "gitadora:Dora": {
        idString: "gitadora:Dora",
        percentMax: 100,
        defaultScoreRatingAlg: "skill",
        defaultSessionRatingAlg: "skill",
        defaultProfileRatingAlg: "skill",
        scoreRatingAlgs: ["skill"],
        sessionRatingAlgs: ["skill"],
        profileRatingAlgs: ["skill"],
        difficulties: ["BASIC", "ADVANCED", "EXTREME", "MASTER"],
        shortDifficulties: {
            BASIC: "D-BSC",
            ADVANCED: "D-ADV",
            EXTREME: "D-EXT",
            MASTER: "D-MAS",
        },
        defaultDifficulty: "EXTREME",
        difficultyColours: {
            BASIC: exports.COLOUR_SET.blue,
            ADVANCED: exports.COLOUR_SET.orange,
            EXTREME: exports.COLOUR_SET.red,
            MASTER: exports.COLOUR_SET.purple,
        },
        grades: ["C", "B", "A", "S", "SS", "MAX"],
        gradeColours: {
            C: exports.COLOUR_SET.purple,
            B: exports.COLOUR_SET.blue,
            A: exports.COLOUR_SET.green,
            S: exports.COLOUR_SET.orange,
            SS: exports.COLOUR_SET.gold,
            MAX: exports.COLOUR_SET.white,
        },
        clearGrade: "A",
        gradeBoundaries: [0, 63, 73, 80, 95, 100],
        lamps: ["FAILED", "CLEAR", "FULL COMBO", "EXCELLENT"],
        lampColours: {
            FAILED: exports.COLOUR_SET.red,
            CLEAR: exports.COLOUR_SET.blue,
            "FULL COMBO": exports.COLOUR_SET.teal,
            EXCELLENT: exports.COLOUR_SET.gold,
        },
        clearLamp: "CLEAR",
        supportedClasses: ["colour"],
        classHumanisedFormat: {
            colour: game_classes_1.GitadoraColours,
        },
        supportsESD: false,
        judgements: ["perfect", "great", "good", "ok", "miss"],
        defaultTable: "Levels (N-1)",
        scoreBucket: "grade",
    },
};
/**
 * Returns the configuration for this game.
 */
function GetGameConfig(game) {
    return GAME_CONFIGS[game];
}
exports.GetGameConfig = GetGameConfig;
/**
 * Returns the configuration for this Game + Playtype.
 * Optionally, a generic parameter - IDStrings - can be passed
 * to indicate what IDString this configuration is for.
 */
function GetGamePTConfig(game, playtype) {
    const idString = `${game}:${playtype}`;
    return GAME_PT_CONFIGS[idString];
}
exports.GetGamePTConfig = GetGamePTConfig;
//# sourceMappingURL=config.js.map