[private]
interactive:
	-@cd ../; just

# Make sure the data in the seeds is ordered correctly.
#
# The seeds have a determinsistic order to make git diffs more sensible!
sort:
	node scripts/sort-seeds.js

# Test that the seeds pass their checks.
test:
	cd scripts/ && pnpm test

# Load the seeds into your local server's database
load:
	cd ../server && pnpm load-seeds