export const neutralSplashes = ["A Rhythm Game Score Manager", "The Rhythm Game Score Manager"];

export const loggedInSplashes = [
	"Splash Text Has The Right To Humour",
	"The Score Tracking Man He Sees Everything Like This",
	"'DROP TABLE scores;--",
	"to be continued...",
	"Blessed Data",
	"No Nonsense",
	"Maybe a little nonsense",
	"Mr Worldwide",
	"Ceci n'est pas un splash text",
	"mowgli, loOK OUT",
	"Swish swoosh pew pew",
	"Do you memorise the notes?",
	"All this scratching is making me itch",
	"Pace yourself",
	"What is this, a crossover episode?",
	"npm install humor",
	"OKNOTOK",
	"Unlimited multiplication of money up to 300%!",
	"What happens if I print a dictionary?",
	"Whatever people say I am...",
	"When the four corners of this coccoon collide...",
	"WE CAN DO BETTER",
	"WE WILL DO BETTER",
	"BREAK YOUR NIHILISM",
	"float chordjack = jack * 0.75f;",
	"malicious walls",
	"my computer called cheesebuger",
	"Unban me from Quaver",
	"...we came in?",
	"isn't this where...",
	"You are simply neglecting the law of large numbers.",
	"I'm using tilt controls!",
	"Relax yourself, girl, please set-tle down",
	"Michael Jackson IS Monty Python.",
	"1.01^365",
	"WARNING: That is not falco",
	"it's been one week since ya looked at me",
	"Producing.",
	"IT AIN'T NO EASY GRAB THEY GOT T",
	"AUTOGLASS REPAIR",
	"AUTOGLASS REPLACE",
	"turn on RANDOM!",
	"It is deliberate.",
	"Buy the golden ninja pack!",
	"WITHIN REASON!",
	"Put the maid dress on.",
	"And it just happens to be fantastically enjoyable.",
	"Touch the statue. I will forgive you.",
	"https://github.com/EpicGames/Signup/pull/10",
	"Have you tried PNPM?",
	"MongoDB is web scale, actually.",
	"▼LTRA ▼IOLENCE EDITION",
	"It's all about the CEO grindset.",
	"through ivy - out middle",
	"The graphics. That's what it's really about.",
	"you could be playing mario galaxy right now",
	"...When yours just crashes?",
	"My Beautiful Score Tracking Fantasy",
	"The Supercharged Score Tracker.",
	"Play ULTRAKILL.",
	"A Cutting-Edge Score Tracker (heh).",
	"Winnipeg is a warm, nice place to live.",
];

// Stuff that's bad for the kids, you know?
export const contentiousSplashes = [
	"Formerly Chucks",
	"Node.js Is Bad Ass Rock Star Tech",
	"i'm obligated to ask for you to seek immediate psychological attention",
];
