import { ChangeOpacity } from "util/color-opacity";
import { FormatTables } from "util/misc";
import QuickTooltip from "components/layout/misc/QuickTooltip";
import Icon from "components/util/Icon";
import React from "react";
import { BMS_TABLES, ChartDocument, COLOUR_SET } from "tachi-common";
import Muted from "components/util/Muted";
import TierlistInfoPart from "./TierlistInfoPart";

export default function BMSOrPMSDifficultyCell({
	chart,
	game,
}: {
	chart: ChartDocument<"bms:7K" | "bms:14K" | "pms:Controller" | "pms:Keyboard">;
	game: "bms" | "pms";
}) {
	const hasLevel = chart.data.tableFolders.length > 0;

	const aiLevel = game === "bms" && (chart as ChartDocument<"bms:7K" | "bms:14K">).data.aiLevel;

	let levelText = "No Rating";
	let backgroundColour = hasLevel ? COLOUR_SET.red : COLOUR_SET.gray;

	if (hasLevel) {
		levelText = FormatTables(chart.data.tableFolders);

		if (game === "bms") {
			// use bms table colour instead of just red/gray.
			// todo: add pms table colours maybe?
			backgroundColour = FindTableColour(chart.data.tableFolders);
		}
	}

	return (
		<td
			style={{
				backgroundColor: ChangeOpacity(backgroundColour, 0.2),
			}}
		>
			{!hasLevel && aiLevel ? (
				<>
					<span>No Rating</span>
					<QuickTooltip tooltipContent="This rating has been generated by AI. Don't put too much trust into it.">
						<div>
							<Muted>AI{aiLevel}</Muted>
						</div>
					</QuickTooltip>
				</>
			) : (
				<span>{levelText}</span>
			)}

			<TierlistInfoPart chart={chart} game={game} />
			{!chart.isPrimary && (
				<QuickTooltip tooltipContent="This chart is an alternate, old chart.">
					<div>
						<Icon type="exclamation-triangle" />
					</div>
				</QuickTooltip>
			)}
		</td>
	);
}

function FindTableColour(
	tableFolders: ChartDocument<"bms:7K" | "bms:14K">["data"]["tableFolders"]
) {
	const lookup = new Map(BMS_TABLES.map((e) => [e.prefix, e.colour]));

	for (const table of tableFolders) {
		const colour = lookup.get(table.table);

		if (colour) {
			return colour;
		}
	}

	return COLOUR_SET.gray;
}
