export const DISALLOWED_CALLBACK_PROTOCOLS = [
    "vbscript:",
    "javascript:",
    "vbs:",
    "data:",
    "mocha:",
    "keyword:",
    "livescript:",
    "ftp:" ,
    "file:" ,
    "gopher:", 
    "acrobat:", 
    "callto:" ,
    "daap:" ,
    "itpc:" ,
    "itms:" ,
    "firefoxurl:", 
    "hcp:",
    "ldap:",
    "mailto:",
    "mmst:",
    "mmsu:",
    "msbd:",
    "rtsp:",
    "mso-offdap:",
    "snews:",
    "news:",
    "nntp:",
    "outlook:",
    "stssync:",
    "rlogin:",
    "telnet:",
    "tn3270:",
    "shell:",
    "sip:",
]